src/lakshya/lakshya/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from utils.views import PartnersView
from utils.urls import urlpatterns as util_urls
from people.urls import urlpatterns as people_urls
from entrepreneurship.urls import urlpatterns as entrepreneurship_urls
from django.conf import settings
from django.contrib.auth import views as auth_views
from views import *


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from lakshya.views import HomeView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^oldhome/?$', 'lakshya.views.get_home_page', name='home'),
    url(r'^/?$', HomeView.as_view(), name='home'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^about$', TemplateView.as_view(template_name="about.html")),
    url(r'^innovation/', include('innovation.urls')),
    url(r'^crowdfunding/', include('crowdfunding.urls')),
    url(r'^research/', include('research.urls')),
    url(r'^nurj/', include('nurj.urls')),
    url(r'^scholarships/', include('scholarships.urls')),
    url(r'^accounts/', include('accounts.urls')),
    (r'^notifications/', include('notification.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    url(r'^logout$', auth_views.logout, {'next_page': '/'},),
    url(r'^partners/', PartnersView.as_view()),
    url(r'^asthra/home$',TemplateView.as_view(template_name="ashtra_home.html")),
    url(r'^asthra/about$', TemplateView.as_view(template_name="about_asthra.html")),
    url(r'^pilot-projects$', TemplateView.as_view(template_name="pilot_projects.html")),
    url(r'^automation/home$', TemplateView.as_view(template_name="automation_home.html")),
    # url(r'^nurj/home$',TemplateView.as_view(template_name="rjournal/home.html")),
    url(r'^contact$',TemplateView.as_view(template_name="contact.html")),    
    url(r'^donate$', "accounts.views.donate_home", name='home'),  
    url(r'^seedfund', "accounts.views.seedfund", name='seedfund'),
    url(r'^payment_redirect$', "accounts.views.payment_redirect", name='payment_redirect'),  
    url(r'^payment-return$', "accounts.views.return_view", name='payment-return'),  
    url(r'^payment-success$',TemplateView.as_view(template_name="payment_success.html")),
    url(r'^payment-failure$', TemplateView.as_view(template_name="payment_failure.html")),
    url(r'^apply$',TemplateView.as_view(template_name="apply-vp.html")),
    url(r'^nem/?$', "nem.views.show_home", name='nem'),  
    url(r'^nem/register/?$', "nem.views.register", name='nem-registration'), 
    url(r'^nem/student/?$', "nem.views.apply_student", name='nem-apply-student'), 
    url(r'^nem/payment-return/?$', "nem.views.return_view", name='nem-payment-return'),    
    url(r'^nem/registration-success/?$', "nem.views.registration_success", name='registration-success'),  
    url(r'^nem/registration-failure/?$', "nem.views.registration_failure", name='registration-failure'),  
    url(r'^corpus$', TemplateView.as_view(template_name="corpus.html")),
    url(r'^newsletter$', TemplateView.as_view(template_name="newsletter.html")),
    url(r'^applicants/?$', "accounts.views.donate_home", name='research_facilitator_applicants'),
    url(r'^hackathon/?',include('hackathon.urls', namespace='hackathon')),
    url(r'^oldpartners/?$', TemplateView.as_view(template_name="partners.html")),
    url(r'^innovationgarage/?', include('innovationgarage.urls', namespace='ig')),
    url(r'^pg/?', include('paymentgateway.urls', namespace='pg')),
   
    # url(r'^$', 'lakshya.views.home', name='home'),
    # url(r'^lakshya/', include('lakshya.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^404$', TemplateView.as_view(template_name="404.html")),
    url(r'^dashboard/?$', DashboardView.as_view(), name='dashboard'),
    url(r'^(?i)IGTeam/?$', TemplateView.as_view(template_name="IGTeam.html")),
    url(r'^(?i)IGAwards/?$', TemplateView.as_view(template_name="IGAwards.html")),
    url(r'^(?i)terms/?$', TemplateView.as_view(template_name="terms.html")),
    # url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
)

urlpatterns += util_urls

urlpatterns += people_urls

urlpatterns += entrepreneurship_urls

urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

handler500 = "lakshya.views.server_error"

src/lakshya/nem/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('nem.views',
)

src/lakshya/nem/forms.py
'''
Created on 08-Aug-2013

@author: srihari
'''
from models import PROFILE_TYPE
from django import forms


class RegistrationForm(forms.Form):
    name = forms.CharField()
    batch = forms.CharField()
    branch = forms.CharField()
    email = forms.EmailField()
    amount = forms.ChoiceField(choices=PROFILE_TYPE)

    

src/lakshya/templates/about_internship_funding.html
{% extends "newbase.html" %}

{% block precss %}
<LINK rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/style_v_1_0_3.css?1"></LINK>
<LINK rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/style_1.css"></LINK>
<style type="text/css">
	.q_and_a p.question {
		margin: 3rem 0 1.5rem;
	}
	.q_and_a li {
		list-style: disc;
	}
</style>
{% endblock precss %}

{% block header %}
{{block.super}}
{% include "submenu_for_old.html" %}
{% endblock header %}

{% block title %}
<title>About Internship Funding - Lakshya</title>
<meta name="description" content="Lakshya an NIT Warangal alumni led registered organization">
{% endblock title %}

{%block header_slide%}
	<a href="/team" title="Team" ><img src="{{STATIC_URL}}img/headers/projects.png" width="990" height="420" alt="Team"></a>
{%endblock header_slide%}

{% block content %}
<div class="content_wrap_old clearfix">
<div class = "content_with_page_title left">
		<div id="blockquote_div">
			<blockquote> "The only source of knowledge is experience."</h3><p>-Albert Einstein</p></blockquote>
		</div> 	
	<h2>About Internship Funding</h2>
	<div class="content_div">
		<div class="q_and_a">

			<p class="question">Why are internship programs important?</p>
			<p class="answer">Internships are a proven way to gain relevant knowledge, skills, and experience while building an important network of experts in the field. It makes the classroom teaching more relevant and increases retention through practical research and real-world applications. More importantly, it exposes students to world class research facilities and opens up opportunities for them to pursue a career in research.</p>

			<p class="question">Are students in need of money?</p>
			<p class="answer">The aim of this program is to give students a first hand experience at world class research facilities. Students are selected based on their enthusiasm to learn and the reputation of the host university. Unlike Scholarships, which is need based, this programs rewards students who often compete with hundreds of candidates across the globe to secure an internship in a reputed university.</p>

			<p class="question">What is the selection process?</p>
			<p class="answer">
				<ul>
				<li>Stage-1: The application portal on the website will be opened in January each year and we will continue to accept applications till the end of the month.</li>
				<li>Stage-2: <a href="http://www.thelakshyafoundation.org/static/docs/RFP-FundingCriteria.pdf">Selection criteria</a> considers both qualitative and quantitative information about the student and the internship opportunity.</li>
				<li>Stage-3: Announcement of results and initiating fund-raising campaign.</li>
				</ul>
			</p>
			<p class="question">How are the funds utilized?</p>
			<p class="answer">Funds are utilized for travel (air fare, visa, local transport), food, and accommodation. Expenses depend on location and duration of the internship.</p>

			<p class="question">What is the impact?</p>
			<p class="answer">
				<ul>
					<li>
						<u>Students</u>: Several students have been funded for their internship in research centers and universities, and for presenting their research work at international conferences. List of beneficiaries can be found <a href="https://docs.google.com/document/d/1RhsI9evTRkUhc9tkHiNO032Ei3UcnOMIAqXhqmCWw8E/edit">here</a>. A majority of them pursue a career in research.
					</li>
					<li>
						<u>Community</u>: Awareness about research has increased in the student community. With inspiration and guidance from seniors, incoming undergraduate batches start working early on basic research in their respective fields. Alumni who benefited from this program have come forward to pitch in with funding and/or contacts to help their juniors.
					</li>
				</ul>
			</p>
			<p class="question">Why should I give?</p>
			<p class="answer">Students are given a soft loan and repay the amount within three years after graduation. This will be utilized to fund more student applicants in future. Hence, your contribution will touch the lives of many students. This is beyond charity, it is an impact investment in your Alma-mater.</p>
		</div>
	</div>
</div>
<div class = "right_navigation_div right">
	<h3>Financial Assistance Program</h3>
	<ul>
		<li><a href="/research/home">Research Facilitator Program Home</a></li>
		<li>About Internship Funding</li>
		<li><a href="/research/apply-rfp/">Apply for Funding</a></li>
	</ul>
</div>
</div>
{% endblock content %}

src/lakshya/templates/about_scholarships_project.html
{% extends "newbase.html" %}

{% block precss %}
<LINK rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/style_v_1_0_3.css?1"></LINK>
<LINK rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/style_1.css"></LINK>
<style type="text/css">
	.q_and_a p.question {
		margin: 3rem 0 1.5rem;
	}
</style>
{% endblock precss %}

{% block header %}
{{block.super}}
{% include "submenu_for_old.html" %}
{% endblock header %}

{% block title %}
<title>About Financial Assistance Project - Lakshya</title>
<meta name="description" content="Lakshya an NIT Warangal alumni led registered organization">
{% endblock title %}

{%block header_slide%}
	<a href="/team" title="Team" ><img src="{{STATIC_URL}}img/headers/projects.png" width="990" height="420" alt="Team"></a>
{%endblock header_slide%}

{% block content %}
<div class="content_wrap_old clearfix">
<div class = "content_with_page_title left">
		<div id="blockquote_div">
			<blockquote> "Education is not an expense... it is an investment"</h3><p>-Lyndon B Johnson, Former President of the United States (1963-1969)</p></blockquote>
		</div> 	
	<h2>About Financial Assistance Program</h2>
	<div class="content_div">
		<div class="q_and_a">

			<p class="question">Why should I sponsor a scholarship?</p>
			<p class="answer">Going by trends, tuition increases by 300% every 5 years and not everyone can afford it. Apart from the tuition fee there are various other expenses including hostel fee, mess charges, text books etc. Supporting these students is not an expense, it is an investment.</p>

			<p class="question">What is the impact?</p>
			<p class="answer">Till date 22 students were benefitted through these scholarships. This kind of financial assistance relieves from immediate stress and helps them concentrate on academics. While some graduated beneficiaries got placed in top MNCs like Samsung, Oracle, and Applied Materials others moved towards their higher education in prestigious institutes like IIM-A and IISc.</p>
			<p class="question">What is the the application process and eligibility criteria?</p>
			<p class="answer">All UG students are eligible to apply and selection is completely based on their financial status. We invite applications from students at the beginning of the academic year which is followed by a stringent verification process. Students are ranked based primarily on their financial status in addition to their academic scores, family support system, prospects of availing and repaying loans. Eligible students are then awarded the scholarship based on the number of slots available.
</p>
			<p class="question">Is this a grant?</p>
			<p class="answer">No. Students have to repay the amount at anytime during the 5 year period after graduation. This amount is used to fund the next set of scholars.</p>
		</div>
	</div>
</div>
<div class = "right_navigation_div right">
	<h3>Financial Assistance Program</h3>
	<ul>
		<li><a href="/scholarships/home">Financial Assistance Program Home</a></li>
		<li>About Financial Assistance Program</li>
		<li><a href="/scholarships/scholars-list/16">List of Scholars</a></li>
		<li><a href="/scholarships/funding-partners">Funding Partners</a></li>
		<li><a href="/scholarships/apply-scholarships">Apply For Scholarships</a></li>		
	</ul>
</div>
</div>
{% endblock content %}

src/lakshya/templates/all_updates.html
{% extends "base.html" %}
{% block title %}
<title>Updates - Lakshya, an NITW alumni led organization</title>
<meta name="description" content="Lakshya an NIT Warangal alumni led registered organization">
{% endblock title %}
{% block content %}
<div class = "content_with_page_title left">
	<h2>Lakshya Updates</h2>
	<div class="content_div">
		{% for update in update_list %}
		<div class="update">
			<h4 id="update-{{update.id}}">{{update.date_of_entry|date:'d-m-y'}}</h4>
			<hr>
			{% if update.photo%}
				<img src="{{update.photo.url}}" />
			{% endif %}
			<p>{{update.update_text|safe}}</p>
		</div>
		{% endfor %}
	</div>
</div>
<div class = "right_navigation_div right">
	<h3>2012</h3>
	<ul>
		<li><a href="/" class="scroll">Home</a></li>
		<li>Updates</li>
	</ul>
</div>
{% endblock content %}

src/lakshya/templates/apply-rfp.html
{% extends "newbase.html" %}

{% block precss %}
<LINK rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/style_v_1_0_3.css?1"></LINK>
<LINK rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/style_1.css"></LINK>
<style type="text/css">
	
</style>
{% endblock precss %}

{% block header %}
{{block.super}}
{% include "submenu_for_old.html" %}
{% endblock header %}

{% block title %}
<title>Apply for Research Facilitator Program</title>
<meta name="description" content="Apply for Research Facilitator Program">
{% endblock title %}

{% block content %}
<div class="content_wrap_old clearfix">
<br>
<h2>Apply for Research Facilitator Program</h2>
<div id="research_main_content" class="left">
*Sign into your google account to view the form<br/>
*Funding criteria - View or download from <a href="{{ STATIC_URL }}docs/RFP-FundingCriteria.pdf">here</a>
<iframe src="https://docs.google.com/forms/d/103SjGtd5gS5TKnDCqrNmTSwJKfQZwEjkDWZ_2a96yTc/viewform?embedded=true" width="760" height="1100" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</div>

<div class = "right_navigation_div right">
	<h3>Financial Assistance Program</h3>
	<ul>
		<li><a href="/research/home">Research Facilitator Program Home</a></li>
		<li><a href="/research/about">About Internship Funding</a></li>
		<li>Apply for Funding</li>

	</ul>
</div>

</div>
{% endblock content %}

src/lakshya/templates/apply_research_success.html
{% extends "base.html" %}

{% block title %}
<title>Apply for Innovation Support Program</title>
<meta name="description" content="Lakshya an NIT Warangal alumni led registered organization">
{% endblock title %}
{% block content %}
<br>
<br>
<p>Congratulations. Your application for Research Facilitator Program is successfully submitted.</p>
{% endblock content %}

src/lakshya/templates/automation_home.html
{% extends "newbase.html" %}

{% block precss %}
<LINK rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/style_v_1_0_3.css?1"></LINK>
<LINK rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/style_1.css"></LINK>
<style type="text/css">
	li {
		list-style: disc;
	}
	#automation_button {
		width: 15% !important;
	}
</style>
{% endblock precss %}

{% block header %}
{{block.super}}
{% include "submenu_for_old.html" %}
{% endblock header %}

{% block title %}
<title>Adminstrative Process Automation - Lakshya</title>
<meta name="description" content="Lakshya an NIT Warangal alumni led registered organization">
{% endblock title %}
{% block meta %}
<script src="http://gettopup.com/releases/latest/top_up-min.js"></script>
{% endblock %}

{%block header_slide%}
	<a href="/team" title="Team" ><img src="{{STATIC_URL}}img/headers/projects.png" width="990" height="420" alt="Team"></a>
{%endblock header_slide%}
{% block content %}
<div class="content_wrap_old clearfix">
<br>
<h2 style="color: #2e93a8;">Administrative Process Automation</h2>
<div id="blockquote_div">
	<blockquote> "One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man."<p>-Elbert Hubbard, American writer, publisher, artist, and philosopher</p></blockquote>
</div>
<div id="intro">
	<p>Applying for official certificates, transcripts or documents from NIT Warangal will be as easy as booking a movie ticket. This has been made possible through IT infrastructure being built by Lakshya together with the institute for the administration.</p>
</div>

<h3 style="color: #2e93a8;"> Certificates that you can apply for </h3>
<ul>
<li> Transcripts </li>
<li> Degree Certificate (Original and Duplicate)</li>
<li> Consolidated Grade Sheets </li>
<li> TC and Migration </li>
<li> Medium of Instruction </li>
</ul>

<a id="automation_button" href="http://www.nitw.ac.in/alumnirequest/select.php">Apply now </a> 
<!--
<h3 style="color: #2e93a8">Planned Next Release</h3>
<p id="release_plan">Request monitoring and Tracking system will be released on <b>February 5th 2013</b></p>
-->
</div>
{% endblock content %}

src/lakshya/templates/payment_failure.html
{% extends "newbase.html" %}
{% block content %}
<div class = "content_with_page_title left">
	<div class="content_div">
		<h3>We are sorry, there was an issue while making the donation. We will look into this and get back to you soon. Please contact us at info@TheLakshyaFoundation.org for any queries.</h3>
	</div>
</div>
{% endblock content %}

src/lakshya/templates/payment_success.html
{% extends "newbase.html" %}
{% block content %}
<div class = "content_with_page_title left">
	<div class="content_div">
		<h3>Thank you for donating and supporting Lakshya!</h3>
	</div>
</div>
{% endblock content %}

src/lakshya/templates/seed_fundraising.html
{% extends "base.html" %}
{% load humanize %} 

{% block title %}
<title>Seed Fund | Lakshya, an NITW alumni led organization</title>
<meta name="description" content="Lakshya an NIT Warangal alumni led registered organization">
{% endblock title %}

{% block meta %}
<LINK rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/tooltip/colortip-1.0-jquery.css"></LINK>
<script src="{{STATIC_URL}}js/jquery.min.js"></script>	
<script type="text/javascript" src="{{STATIC_URL}}js/tooltip/colortip-1.0-jquery.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/tooltip/script.js"></script>

<script type="text/javascript">
$(function(){
	$("#why_corpus").hide();
	$("#why_seed").show();
	$('#why_seed_link').addClass("seed-link-selected")
	$('#why_corpus_link').addClass("seed-link-not-selected")	
	$("#why_seed_link").click(function(){
		$("#why_corpus").hide();
		$("#why_seed").show();
		$('#why_seed_link').addClass("seed-link-selected")
		$('#why_seed_link').removeClass("seed-link-not-selected")
		$('#why_corpus_link').removeClass("seed-link-selected")
		$('#why_corpus_link').addClass("seed-link-not-selected")

	});
	$("#why_corpus_link").click(function(){
		$("#why_corpus").show();
		$("#why_seed").hide();
		$('#why_seed_link').removeClass("seed-link-selected")
		$('#why_seed_link').addClass("seed-link-not-selected")
		$('#why_corpus_link').addClass("seed-link-selected")
		$('#why_corpus_link').removeClass("seed-link-not-selected")
	});

    // $('#donation_results').masonry({
    // // options
    //     itemSelector : '.result_div',
    // });	

    // $('#pledge_results').masonry({
    // // options
    //     itemSelector : '.result_div',
    // });	
});
</script>
{% endblock %}

{% block content %}
	<img src="{{STATIC_URL}}img/seed_capital_final.jpg" width="990px" />

	<div id="seedcapital_main" class="left">
		{% if show_success_message %}
		<div id="show_pledge_thankyou">
			<p>Thank you for pledging. Fulfill your pledge by <a href="/donate">donating now</a></p>
		</div>
		{% else %}
<!--		<p><b>Thank You!</b></p>
		<p>For coming here to help us sustain, grow and make big things happen at NIT Warangal</p>-->
		{% endif %}
		<h2 class="center, cB">Make your pledge</h2>

		<form id="pledge_form" action="/seedfund" method="post">{% csrf_token %}
		    {{ form.non_field_errors }}
		    <div id="name_div" class="fieldWrapper left">
		        {{ form.name.errors }}
		        <label for="id_name">Name</label>
		        {{ form.name }}
		    </div>
		    <div id="email_div" class="fieldWrapper left">
		        {{ form.email.errors }}
		        <label for="id_email">Email</label>
		        {{ form.email }}
		    </div>
		    <div class="cB"></div>
		    <div id="rs_or_dollar_div" class="fieldWrapper left">
		    	<label>Amount</label>
				{% if is_dollar %}
				<p style="font-size:21px; margin-top:10px">$ 500 <a href="#" class="blue" title="<div style='padding-left:500px;'><u>Reason for $500 (USD) over Rs.10,000 (INR) for alumni based in Advanced Economies</u><br>The amounts we ask people are related to spending power of the alumni. Direct conversion of Rs.10,000 gives us ~$190 for all alumni,<br> including those based in advance economies. <br>We believe you can give a little more and help us cover the target quicker, without having to make serious changes in your monthly budget.<br>
				Consider this: If everyone gives in Rs.10,000, 150 will alumni will have to contribute. <br>If 30 of them contribute $500 each, we only need 70 more to contribute Rs.10,000 each. <br>
				That's at least 50 less people to approach and, more importantly, several hours saved which can be used for our core-focus areas.  
				Hence, our sincere request to give, and to give a little more.</div>">[?]</a></p>
				{% else %}
				<p style="font-size:21px; margin-top:10px">Rs 10,000 </p>
				{% endif %}

		    </div>
		    <div class="fieldWrapper left">
		        {{ form.batch.errors }}
		        <label for="id_batch">Batch</label>
		        {{ form.batch }}
		    </div>
		    <div id="month_of_donation_div" class="fieldWrapper left">
		        {{ form.month_of_donation.errors }}
		        <label for="id_month_of_donation">Will donate by</label>
		        {{ form.month_of_donation }}
		    </div>
		    <div id="pledge_submit_div">
		    	<input class="pledge_submit" class="left" type="submit" value="Pledge Now" />
		    </div>
		    <span class="cB"></span>
		</form>

		<div id="seed_links">
		<span id="why_seed_link" >Why Seed Capital</span>&nbsp&nbsp|&nbsp&nbsp<span id="why_corpus_link" >Why Corpus</span>
		</div>

		<div id="why_seed">
			<p>Lakshya is a non-profit that has a unique goal -<i> to help build an ecosystem of research and entrepreneurship through creativity and innovation at NIT Warangal.</i></p>

			<p>Every effort needs sound financial footing to deliver and sustain. Raising a corpus is in itself a massive task and it will entail expenses. It is a long term commitment and, through this seed capital, we are preparing ourselves to go the distance.
			</p>
			<p>Target: <b>Rs.15,00,000 </b> by Oct 2013</p>
		</div>

		<div id="why_corpus">
			<p>The results we've delivered such as NIT Warangal's first patent application and our effective model for innovation and research support has also gotten the attention of the english and telugu press.</p>

			<p>We now have to grow and grow rapidly to achieve our vision. Having a corpus will enable us to take up several more projects having a wider and deeper impact in NIT Warangal. We can build resources in line with our goal and take bold decisions, a necessity in an era where innovation and risk go hand in hand.</p>	

			<p>Target: <b>Rs.5 crores </b> by June 2016</p>
		</div>

<!--		<h2 class="center">Seed Captial Contributions</h2>-->

		<h3>Alumni who have pledged</h3>
		<hr>
			<div id="pledge_results">
			{% for pledge in pledges %}
					<div class="result_div">
						{% if pledge.name|length > 20 %}
							<h2>{{ pledge.name|slice:":18" }}..</h2>
						{% else %}
							<h2>{{ pledge.name }}</h2>						
						{% endif %}
						<p>{{ pledge.batch }}</p>
						<p>{% if pledge.rs_or_dollar == 10000 %}Rs.{{ pledge.donation_amount|floatformat:"0"|intcomma }} {% else %} $500 {% endif %} pledged</p>
					</div>
				{% endfor %}
			</div>

		<div class="cB"></div>
		<h3 class="cB">Alumni who have donated</h3>
		<hr>
		<div>
			<div id="donation_results">
				{% for donation in donations %}
					<div class="result_div">
						{% if donation.name|length > 20 %}
							<h2>{{ donation.name|slice:":18" }}..</h2>
						{% else %}
							<h2>{{ donation.name }}</h2>						
						{% endif %}
						<p>{{ donation.batch }}</p>
						<p>{% if donation.rs_or_dollar == 10000 %}Rs.{{ donation.donation_amount|floatformat:"0"|intcomma }} {% else %} $500 {% endif %} donated</p>
					</div>
				{% endfor %}
			</div>
		</div>
		<div class="cB"></div>
    </div>
    <div id="seedfund_right_panel" class="left">
<!--     	<div id="donate_panel">
    		<a href="/donate-seedfund">Donate and fulfill your pledge</a>
    	</div> -->

	    <div id="seed_stats">
	    	<!--<h2>Stats</h2>-->
	    	<div class="stats_block">
		    	<div class="stats_number">15,00,000</div>
		    	<div class="stats_description">Target</div>
	    	</div>
	    	<div class="stats_block">
		    	<div class="stats_number">{{ pledge_percentage }}</div>
		    	<div class="stats_description">% of Target Amount Pledged</div>
	    	</div>
		</div>
	   	<hr>

	    <div id="ceo_message_panel" >
	    	<p><b>Dear alumni,</b></p>
	    	<p>NIT Warangal has given us fond memories, great friends, and a top education. Its time we give back and in a big way. Lakshya aims to do just that and we've delivered some fine results so far. Support from the alumni, institute, and industry is imperative but strong foundations are laid on sound financial footing. </p><p>A corpus will help realize our collective vision for NIT Warangal, the seed capital is the first small step to enter the big league.</p>
	    	<p>Thanks,</p>
	    	<img src="{{STATIC_URL}}img/anand-sign.png" width="120px" height="50px"/>
	    	<p>Anand Rajagopalan, CEO</p>
	    </div>

    </div>
{% endblock content %}